
gg_plot_strat_nested  = function (DIR_NPLCM, strata_weights = NULL, truth = NULL, RES_NPLCM = NULL){
  
  if (!is_jags_folder(DIR_NPLCM)) {
    stop("==[baker] Oops, not a folder baker recognizes. Try a folder generated by baker, e.g., a temporary folder?==")
  }
  data_nplcm <- dget(file.path(DIR_NPLCM, "data_nplcm.txt"))
  model_options <- dget(file.path(DIR_NPLCM, "model_options.txt"))
  mcmc_options <- dget(file.path(DIR_NPLCM, "mcmc_options.txt"))
  parsed_model <- assign_model(model_options, data_nplcm)
  is_nested <- parsed_model$nested
  cat("==[baker] plotting etiology regression with >>", c("nested", 
                                                          "non-nested")[2 - is_nested], "<< model==\n")
  new_env <- new.env()
  source(file.path(DIR_NPLCM, "jagsdata.txt"), local = new_env)
  bugs.dat <- as.list(new_env)
  rm(new_env)
  if (!is.null(RES_NPLCM)) {
    res_nplcm <- RES_NPLCM
  }
  else {
    res_nplcm <- coda::read.coda(file.path(DIR_NPLCM, "CODAchain1.txt"), 
                                 file.path(DIR_NPLCM, "CODAindex.txt"), quiet = TRUE)
  }
  print_res <- function(x) plot(res_nplcm[, grep(x, colnames(res_nplcm))])
  get_res <- function(x) res_nplcm[, grep(x, colnames(res_nplcm))]
  n_samp_kept <- nrow(res_nplcm)
  ncol_dm_Eti <- ncol(bugs.dat$Z_Eti)
  Jcause <- bugs.dat$Jcause
  Nd <- bugs.dat$Nd
  Nu <- bugs.dat$Nu
  likelihood <- model_options$likelihood
  Y <- data_nplcm$Y
  X <- data_nplcm$X
  Eti_formula <- likelihood$Eti_formula
  is_discrete_Eti <- is_discrete(data.frame(X, Y)[Y == 1, , 
                                                  drop = FALSE], Eti_formula)
  Z_Eti <- stats::model.matrix(Eti_formula, data.frame(X, Y)[Y == 
                                                               1, , drop = FALSE])
  ncol_dm_Eti <- ncol(Z_Eti)
  Eti_colname_design_mat <- attributes(Z_Eti)$dimnames[[2]]
  attributes(Z_Eti)[names(attributes(Z_Eti)) != "dim"] <- NULL
  unique_Eti_level <- unique(Z_Eti)
  n_unique_Eti_level <- nrow(unique_Eti_level)
  Eti_stratum_id <- apply(Z_Eti, 1, function(v) which(rowSums(abs(unique_Eti_level - 
                                                                    t(replicate(n_unique_Eti_level, v)))) == 0))
  rownames(unique_Eti_level) <- 1:n_unique_Eti_level
  colnames(unique_Eti_level) <- Eti_colname_design_mat
  betaEti_samp <- array(t(get_res("^betaEti")), c(ncol_dm_Eti, 
                                                  Jcause, n_samp_kept))
  linpred <- function(beta, design_matrix) {
    design_matrix %*% beta
  }
  out_Eti_linpred <- array(apply(betaEti_samp, 3, linpred, 
                                 design_matrix = unique_Eti_level), c(nrow(unique_Eti_level), 
                                                                      Jcause, n_samp_kept))
  pEti_samp <- aperm(apply(out_Eti_linpred, c(1, 3), softmax), 
                     c(2, 1, 3))
  Eti_prob_scale <- pEti_samp
  Eti_mean <- apply(Eti_prob_scale, c(1, 2), mean)
  Eti_q <- apply(Eti_prob_scale, c(1, 2), quantile, c(0.025, 
                                                      0.975))
  Eti_overall <- apply(Eti_prob_scale, c(1, 3), mean)
  Eti_overall_mean <- rowMeans(Eti_overall)
  Eti_overall_sd <- apply(Eti_overall, 1, sd)
  Eti_overall_q <- apply(Eti_overall, 1, quantile, c(0.025, 
                                                     0.975))
  Eti_prob_scale <- aperm(Eti_prob_scale, c(3, 1, 2))
  user_weight <- rep(1/n_unique_Eti_level, n_unique_Eti_level)
  if (!is.null(strata_weights) && strata_weights == "empirical") {
    strat_ind <- match_cause(apply(unique_Eti_level, 1, paste, 
                                   collapse = ""), apply(stats::model.matrix(Eti_formula, 
                                                                             data_nplcm$X[data_nplcm$Y == 1, ]), 1, paste, collapse = ""))
    empirical_wt <- rep(NA, nrow(unique_Eti_level))
    for (s in seq_along(empirical_wt)) {
      empirical_wt[s] <- mean(strat_ind == s)
    }
    user_weight <- empirical_wt
  }
  else {
    if (!is.null(strata_weights) && length(strata_weights == 
                                           n_unique_Eti_level)) {
      user_weight <- strata_weights
    }
  }
  Eti_overall_usr_weight <- apply(Eti_prob_scale, 1, function(S) t(S) %*% 
                                    matrix(user_weight, ncol = 1))
  Eti_overall_mean_usr_weight <- rowMeans(Eti_overall_usr_weight)
  Eti_overall_q_usr_weight <- apply(Eti_overall_usr_weight, 
                                    1, quantile, c(0.025, 0.975))
  # par(mfcol = c(1 + n_unique_Eti_level, Jcause), mar = c(3, 
  #                                                        8, 1, 0))
  ## plot histograms of the posterior probabilities for each stratum 
  plot_list <- list()
  for (site in 1:n_unique_Eti_level) {
    etiData = data.frame(Eti_prob_scale[,site,])
    names(etiData) = cause_list
    plotData = melt(etiData,id.vars = NULL)
    names(plotData) = c("cause", "prob")
    
    # compute posterior means 
    summaryData <- plotData %>%
      group_by(cause) %>%
      summarise(eti_mean = mean(prob))
    
    plot <- ggplot(plotData, aes(x=prob)) +
      geom_histogram(fill="#BFE4DE") + 
      geom_vline(data=summaryData, 
                 mapping = aes(xintercept=eti_mean), colour="#336E8C", linetype="dashed", size=1.25) +
      facet_wrap(~cause) +
      labs(title=paste0("Plot of posterior etiology probabilities for stratum: ", site, "\n User weights: ", (round(user_weight[site]))),
           subtitle = "Mean posterior probability displayed as dashed line",
           x = "Etiology", y ="Samples")
    if (!is.null(truth$allEti)) {
      plot <- plot + geom_vline(mapping = aes(xintercept= truth$allEti[[site]][[j]]), colour = "black")
    } else {
      plot <- plot 
    }
    plot_list[[site]] <- plot 
  }
  # shape the overall marginal etiology probabilities as a data frame 
  overallEti = data.frame(Eti_overall_usr_weight)
  overallEti$cause = cause_list
  overallEti = melt(overallEti, id.vars = "cause", value.name = "prob")
  
  # compute the posterior means 
  summaryEti <- overallEti %>%
    group_by(cause) %>%
    summarise(overall_mean = mean(prob))
  
  ## add the plot of overall marginal eti probabiltiies (across sites)
  plot_list[[n_unique_Eti_level+1]] <-  ggplot(overallEti, aes(x=prob)) +
    geom_histogram(fill="#E4CDDD") +
    geom_vline(data=summaryEti, 
               mapping = aes(xintercept=overall_mean), colour="#726CA8", linetype="dashed", size=1.25) +
    facet_wrap(~cause)+
    labs(title="Marginal posterior etiology probabilities (across all sites) \n Computed using stratum weights",
         subtitle= "Overall marginal posterior mean displayed as dashed line",
         x = "Etiology", y ="Samples")
  
  return(plot_list)
}

