
##----------------------------
### Function to plot stratified by a discrete covariate using ggplot 
## Requres the ggplot, dplyr, and reshape2 packages to be loaded 
## The output is a list of plots, one for each stratum 
## The last plot in the list is of the marginal posterior etiology probabiltiies computed across all strata 
## The plot results are similar to plot_etiology_strat but users have more flexibility to customize with ggplot functions (e.g. plot themes)
##----------------------------

gg_plot_etiology_strat <- function(DIR_NPLCM,strata_weights=NULL,truth=NULL){
  
  # Check if result folder filepath is correctly specified 
  if (!is_jags_folder(DIR_NPLCM)){
    stop("==[baker] oops, not a folder baker recognizes. 
         Try a folder generated by baker, e.g., a temporary folder?==")
  }
  
  # Read in the nplcm data and model options 
  data_nplcm <- dget(file.path(DIR_NPLCM,"data_nplcm.txt"))  
  model_options <- dget(file.path(DIR_NPLCM,"model_options.txt"))  
  
  if (is.null(data_nplcm)|is.null(model_options)){
    stop("==[baker] oops, nplcm data and model options settings not found in the result folder!=")
  }
  
  ## get the list of causes 
  cause_list = model_options$likelihood$cause_list
  
  ## read in the posterior samples 
  new_env <- new.env()
  source(file.path(DIR_NPLCM,"jagsdata.txt"),local=new_env)
  bugs.dat <- as.list(new_env)
  rm(new_env)
  
  res_nplcm <- coda::read.coda(file.path(DIR_NPLCM,"CODAchain1.txt"),
                               file.path(DIR_NPLCM,"CODAindex.txt"),
                               quiet=TRUE)
  print_res <- function(x) plot(res_nplcm[,grep(x,colnames(res_nplcm))])
  get_res   <- function(x) res_nplcm[,grep(x,colnames(res_nplcm))]
  
  # structure the posterior samples:
  JBrS_1        <- ncol(bugs.dat$MBS_1) # number of pathogens in MBS1
  n_samp_kept   <- nrow(res_nplcm)      # number of posterior sample after burn-in
  Jcause        <- bugs.dat$Jcause      # number of causes
  Nd            <- bugs.dat$Nd          # case size
  Nu            <- bugs.dat$Nu          # control size
  n_unique_Eti_level <- bugs.dat$n_unique_Eti_level  # number of stratums
  
  ## Check if model has been fit with a discrete covariate
  if (is.null(n_unique_Eti_level)){
    stop("==[baker] Number of stratums is null! ? ==")
  }
  
  # etiology:
  plotid_Eti <- which(data_nplcm$Y==1) #want the etiology for cases only 
  #  format eti probabilities into an array by stratum and cause
  Eti_prob_scale <- array(get_res("pEti"),c(n_samp_kept,n_unique_Eti_level,Jcause))
  
  # weight to marginalize posterior etiology distributions
  user_weight <- rep(1/n_unique_Eti_level,n_unique_Eti_level)
  if(!is.null(strata_weights) && length(strata_weights==n_unique_Eti_level)){
    user_weight <- strata_weights
  }
  
  # marginalized posterior etiology over all sites using user-defined weights
  Eti_overall_usr_weight <- apply(Eti_prob_scale,1,function(S) t(S)%*%matrix(user_weight,ncol=1))

  
  plot_list <- list()
  for(site in 1:n_unique_Eti_level){
    
    # shape probabilities array into dataset for ggplot 
    etiData = data.frame(Eti_prob_scale[,site,])
    names(etiData) = cause_list
    plotData = melt(etiData,id.vars = NULL)
    names(plotData) = c("cause", "prob")
    
    # compute posterior means 
    summaryData <- plotData %>%
      group_by(cause) %>%
      summarise(eti_mean = mean(prob))
    
    ## plot histograms of the posterior probabilities for each stratum 
    plot_list[[site]] <- ggplot(plotData, aes(x=prob)) +
      geom_histogram(fill="#ffc04d") + 
      geom_vline(data=summaryData, 
                 mapping = aes(xintercept=eti_mean), colour="#005b96", linetype="dashed") +
      facet_wrap(~cause) +
      labs(title=paste0("Plot of posterior etiology probabilities for stratum: ", site),
           subtitle = "Mean posterior probability displayed as dashed line",
           x = "Etiology", y ="Samples")
  }
  
  # shape the overall marginal etiology probabilities as a data frame 
  overallEti = data.frame(Eti_overall_usr_weight)
  overallEti$cause = cause_list
  overallEti = melt(overallEti, id.vars = "cause", value.name = "prob")
  
  # compute the posterior means 
  summaryEti <- overallEti %>%
    group_by(cause) %>%
    summarise(overall_mean = mean(prob))
  
  ## add the plot of overall marginal eti probabiltiies (across sites)
  plot_list[[n_unique_Eti_level+1]] <-  ggplot(overallEti, aes(x=prob)) +
    geom_histogram(fill="#ffc04d") +
    geom_vline(data=summaryEti, 
               mapping = aes(xintercept=overall_mean), colour="#005b96", linetype="dashed") +
    facet_wrap(~cause)+
    labs(title="Marginal posterior etiology probabilities (across all sites)",
         subtitle= "Overall marginal posterior mean displayed as dashed line",
         x = "Etiology", y ="Samples")
  
  return(plot_list)
  
  }
